# Generated by Django 3.2.4 on 2021-06-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210608_2110'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
